### ISSUE TITLE
`CellVariableVector` contains non-`Cell` variables

### ISSUE THREAD

**Issue by pgrete** [parthenon-hpc-lab/parthenon#869] opened 2023-05-02 19:00 UTC
This may likely be fixed in the overhauls of the variable machinery @lroberts36 is currently working on, but I'm reporting nevertheless (as this was the root cause of the Ascent issue wrt to mismatch in variable dimensions).

**Comment by lroberts36** [comment] 2023-06-01 23:29
`CellVariableVector` is now `VariableVector` and contains non-`Cell` variables, but this is not a bug. We could also include `*VariableVector` for each of the different topological types if this was useful though.

**Comment by lroberts36** [comment] 2024-04-10 19:46
closing since `CellVariableVector` doesn't exist anymore.

**Closed as completed by lroberts36** 2024-04-10 19:46 UTC
Labels: bug
