### ISSUE TITLE
Badges need an update?

### ISSUE THREAD

**Issue by Yurlungur** [parthenon-hpc-lab/parthenon#770] opened 2022-10-27 00:20 UTC
Despite the CI on develop currently passing, the badges on the README indicate failing CI. Did something go wrong with them when we migrated to the new project space?

**Comment by pgrete** [comment] 2022-10-27 06:37
Both tests actually failed.

The extended one because the old runner picked up the job. I now turned the old runner off.

The short one failed because of a timeout in the advection test. I'm investigating.

**Comment by pgrete** [comment] 2022-10-27 09:38
Just confirmed on my own laptop, this is a legit bug introduced by #755 (the previous merge commit to `develop` does not run into a timeout)

**Comment by pgrete** [comment] 2022-10-27 09:59
Can someone else please look at/reproduce this, e.g., @lroberts36 or @bprather ?

With current develop following command (which is run as part of the regression tests) hangs at the final output:
```bash
~/src/parthenon/build-cuda-mpi]
$ mpirun -np 2 ./example/advection/advection-example -i ../tst/regression/test_suites/output_hdf5/parthinput.advection parthenon/mesh/nx1=64
...
cycle=568 time=9.9843749999998965e-01 dt=1.5625000000103473e-03 zone-cycles/wsec_step=6.58e+05 wsec_total=3.21e+01 wsec_step=5.06e-02 zone-cycles/wsec=6.58e+05 wsec_AMR=4.10e-05
^ last output before hang
```
using the previous version (commit 0c6a56ae93e53c2f4739d30c254d544d3c0a159e) works fine.
Note that is only hangs for MPI runs, serial runs go through fine.

If you can reproduce, how can any change in #755 introduce this behavior?!

**Comment by pgrete** [comment] 2022-10-27 10:28
Found it...
```diff
--- a/src/driver/driver.cpp
+++ b/src/driver/driver.cpp
@@ -20,6 +20,7 @@
 #include "driver/driver.hpp"
 
 #include "bvals/cc/bvals_cc_in_one.hpp"
+#include "globals.hpp"
 #include "interface/update.hpp"
 #include "mesh/mesh.hpp"
 #include "mesh/meshblock.hpp"
@@ -70,7 +71,7 @@ DriverStatus EvolutionDriver::Execute() {
 
   // Output a text file of all parameters at this point
   // Defaults must be set across all ranks
-  if (Globals::my_rank == 0) DumpInputParameters();
+  DumpInputParameters();
 
   Kokkos::Profiling::pushRegion("Driver_Main");
   while (tm.KeepGoing()) {
@@ -199,7 +200,7 @@ void EvolutionDriver::DumpInputParameters() {
   auto archive_settings =
       pinput->GetOrAddString("parthenon/job", "archive_parameters", "false",
                              std::vector<std::string>{"true", "false", "timestamp"});
-  if (archive_settings != "false") {
+  if (archive_settings != "false" && Globals::my_rank == 0) {
     std::ostringstream ss;
     if (archive_settings == "timestamp") {
       auto itt_now =
```
As the comment in the source says, "defaults must be set across all ranks" but the default for outputting the param file was just set by rank 0, which is why the final output hang (as the params output in the hdf5 file written in parallel across ranks was out of sync).
I'll push the fix to #740, which was accidentally already merged with #755 (but with the mixed ordering of indices), and then merge #740, which should bring everything back to working condition *fingerscrossed*

**Comment by Yurlungur** [comment] 2022-10-27 14:00
Phew. Sorry for the mess here... 

It looks to me like auto merge is being overzealous so we should perhaps stop using it

**Comment by lroberts36** [comment] 2022-10-27 15:39
Yeah, yesterday automerge triggered way before tests had finished on the flux correction in one PR as well.

**Comment by pgrete** [comment] 2022-10-27 16:39
This should not happen any more. I just reactivated that the unit and regression tests are mandatory for a PR to (auto)merge.
Short tests work again (incl the badge) and the extended test failed because of the timing in the overlapping space instances test.
I'm in favor of removing that test as we don't need that feature at the moment and it's a leftover from the original "making buffer packing fast" attempts.

**Comment by Yurlungur** [comment] 2022-10-27 16:49
> This should not happen any more. I just reactivated that the unit and regression tests are mandatory for a PR to (auto)merge.
Short tests work again (incl the badge) and the extended test failed because of the timing in the overlapping space instances test.

Sounds good. Thanks for the fix!

> I'm in favor of removing that test as we don't need that feature at the moment and it's a leftover from the original "making buffer packing fast" attempts.

Agreed. Let's remove it.

**Closed as completed** 2022-11-01 08:33 UTC
